### ISSUE TITLE
NoSuchMethodError being thrown for ScrollListToElementWithText in Katalon 7.0.8

### ISSUE THREAD

**Issue by scsmith5593** [detroit-labs/katalon-mobile-util#25]
Hi,

After upgrading Katalon (from 6.3.3 to 7.0.8) and running a test that was previously working, I'm getting an error when I do ScrollListToElementWithText:

java.lang.NoSuchMethodError: com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords.delay(Ljava/lang/Object;)V
	at com.detroitlabs.katalonmobileutil.touch.Scroll.scrollEntireList(Scroll.java:259)
	at com.detroitlabs.katalonmobileutil.touch.Scroll.scrollListToElementWithXPath(Scroll.java:193)
	at com.detroitlabs.katalonmobileutil.touch.Scroll.scrollListToElementWithText(Scroll.java:131)
	at com.detroitlabs.katalonmobileutil.touch.Scroll.scrollListToElementWithText(Scroll.java:102)
	at com.detroitlabs.katalonmobileutil.touch.Scroll$scrollListToElementWithText.call(Unknown Source)
	at About Screen Links - Contact STM.run(About Screen Links - Contact STM:23)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:337)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:307)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:299)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:233)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:114)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:105)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1573493983721.run(TempTestCase1573493983721.groovy:23)

**Comment by ctrevarthen** [comment]
Hi @scsmith5593 ,

Looks like one of the underlying Katalon method signatures changed. I've updated the libraries to use the new Katalon Studio 7 versions and released version 1.14.0 of katalon-mobile-util: https://github.com/detroit-labs/katalon-mobile-util/releases/tag/1.14.0

Please let me know if that resolves your issue.

-- Chris

**Comment by scsmith5593** [comment]
Hi, @ctrevarthen,

Perfect--that fixed it!  Thanks so much for the quick resolution!

--Stephanie
